env:
  node: true
  jest/globals: true

extends:
  - airbnb
  - '@react-native-community'
  - 'plugin:prettier/recommended'
  - prettier/react
parser: babel-eslint
plugins:
  - jest
  - react
  - react-hooks

globals:
  fetch: true

settings:
  import/resolver:
    babel-module:

rules:
  'prettier/prettier': 'error'
  no-restricted-imports:
    - error
    - paths:
        - name: react-native-gesture-handler
          importNames:
            - TouchableOpacity
            - TouchableNativeFeedback
            - TouchableHighlight
            - TouchableWithoutFeedback
          message: Please import it from 'react-native' instead.
  # Override airbnb config to allow `for of` statements, need to specify everything but ForOfStatement
  no-restricted-syntax:
    - error
    - selector: ForInStatement
      message:
        for..in loops iterate over the entire prototype chain, which is virtually
        never what you want. Use Object.{keys,values,entries}, and iterate over the resulting
        array.
    - selector: LabeledStatement
      message:
        Labels are a form of GOTO; using them makes code confusing and hard to
        maintain and understand.
    - selector: WithStatement
      message:
        '`with` is disallowed in strict mode because it makes code impossible to
        predict and optimize.'

  no-underscore-dangle:
    - error
    - allowAfterThis: true

  react/jsx-filename-extension:
    - 0

  react/prop-types:
    - 0
# https://github.com/typescript-eslint/typescript-eslint/issues/109#issuecomment-536160947
overrides:
  - files:
      - '**/*.ts'
      - '**/*.tsx'
    env:
      es6: true
      node: true
      jest/globals: true
    extends:
      - airbnb
      - 'plugin:@typescript-eslint/recommended'
      - 'plugin:react/recommended'
      - 'plugin:prettier/recommended'
      - prettier/react
      - 'prettier/@typescript-eslint'
    parser: '@typescript-eslint/parser'
    parserOptions:
      ecmaFeatures:
        jsx: true
      ecmaVersion: 2018
      sourceType: module
      project: './tsconfig.json'
    rules:
      react/jsx-filename-extension:
        - 0
      '@typescript-eslint/explicit-function-return-type':
        - warn
        - allowExpressions: true
          allowTypedFunctionExpressions: true
      no-restricted-imports:
        - error
        - paths:
            - name: react-native-gesture-handler
              importNames:
                - TouchableOpacity
                - TouchableNativeFeedback
                - TouchableHighlight
                - TouchableWithoutFeedback
              message: Please import it from 'react-native' instead.
    settings:
      react:
        version: detect
      import/resolver:
        babel-module: