export const TIP_LIST = '@TIPTAPSTORE:TIP_LIST';
export const FINISHED_ONBOARDING = '@TIPTAPSTORE:FINISHED_ONBOARDING';
export const FAVORITE_TIP_LIST = '@TIPTAPSTORE:FAVORITE_TIP_LIST';
export const SELECTED_TIP = '@TIPTAPSTORE:SELECTED_TIP';
